[env:nucleo_l432kc]
platform = ststm32
board = nucleo_l432kc
framework = arduino
monitor_speed = 115200

; Download the micro-ROS library directly from their official repository
lib_deps =
    https://github.com/micro-ROS/micro_ros_arduino.git#humble

; Tell the compiler where to find the pre-compiled micro-ROS C libraries
build_flags =
    -L ./.pio/libdeps/nucleo_l432kc/micro_ros_arduino/src/cortex-m4/
    -l microros